"""Add the v1.3.11 translation keys to every language file.

* ``batch_import.*`` — the « Importer plusieurs éléments » batch dialog;
* ``profiles.import`` / ``profiles.import_tooltip`` — relabeled to the
  unambiguous « Importer un profil » (.zip);
* ``profiles.import_filter`` — file picker filter (.zip + legacy .rcmprofile);
* ``profiles.conflict_*`` — import-name conflict resolution
  (replace / create a copy / cancel).

Re-dumps each file with the exact original formatting
(``json.dumps(..., ensure_ascii=False, indent=4)`` + trailing newline, LF),
so the only diff is the changed/added keys. The i18n parity test then
verifies the 10 languages match exactly.
"""
from __future__ import annotations

import json

TRANS = {
    "fr": {
        "batch_import.title": "Importer plusieurs éléments",
        "batch_import.count": "{count} élément{s} détecté{s}",
        "batch_import.to_choose": "ℹ️ Destination à choisir",
        "batch_import.detected": "✓ Détecté : {label}",
        "batch_import.manual": "Destination choisie manuellement",
        "batch_import.import_button": "Importer les {count} élément{s}",
        "batch_import.imported": "{count} élément{s} importé{s}",
        "batch_import.failed": "Certains éléments ont échoué : {names}",
        "batch_import.destination_tooltip": "Destination réelle dans cette catégorie (vide = la catégorie elle-même)",
        "batch_import.choose_category": "Choisir une catégorie",
        "batch_import.choose_destination": "Choisir une destination",
        "batch_import.choose_weapon": "Choisir une arme",
        "batch_import.no_sublevel": "Aucun sous-niveau — la catégorie est la destination",
        "batch_import.new_destination": "+ Nouvelle destination",
        "batch_import.new_destination_title": "Nouvelle destination",
        "batch_import.new_destination_prompt": "Nom de la nouvelle destination :",
        "batch_import.new_destination_tooltip": "Créer une nouvelle destination dans cette catégorie (action explicite)",
        "profiles.import": "Importer un profil",
        "profiles.import_tooltip": "Importer un profil (.zip)",
        "profiles.import_filter": "Profil RCM (*.zip *.rcmprofile);;Tous les fichiers (*)",
        "profiles.conflict_title": "Un profil existe déjà",
        "profiles.conflict_text": "Un profil « {name} » existe déjà. Que voulez-vous faire ?",
        "profiles.conflict_replace": "Remplacer",
        "profiles.conflict_copy": "Créer une copie",
    },
    "en": {
        "batch_import.title": "Import multiple items",
        "batch_import.count": "{count} item{s} detected",
        "batch_import.to_choose": "ℹ️ Destination to choose",
        "batch_import.detected": "✓ Detected: {label}",
        "batch_import.manual": "Destination chosen manually",
        "batch_import.import_button": "Import the {count} item{s}",
        "batch_import.imported": "{count} item{s} imported",
        "batch_import.failed": "Some items failed: {names}",
        "batch_import.destination_tooltip": "Real destination inside this category (empty = the category itself)",
        "batch_import.choose_category": "Choose a category",
        "batch_import.choose_destination": "Choose a destination",
        "batch_import.choose_weapon": "Choose a weapon",
        "batch_import.no_sublevel": "No sub-level — the category is the destination",
        "batch_import.new_destination": "+ New destination",
        "batch_import.new_destination_title": "New destination",
        "batch_import.new_destination_prompt": "Name of the new destination:",
        "batch_import.new_destination_tooltip": "Create a new destination in this category (explicit action)",
        "profiles.import": "Import a profile",
        "profiles.import_tooltip": "Import a profile (.zip)",
        "profiles.import_filter": "RCM Profile (*.zip *.rcmprofile);;All files (*)",
        "profiles.conflict_title": "Profile already exists",
        "profiles.conflict_text": "A profile « {name} » already exists. What do you want to do?",
        "profiles.conflict_replace": "Replace",
        "profiles.conflict_copy": "Create a copy",
    },
    "es": {
        "batch_import.title": "Importar varios elementos",
        "batch_import.count": "{count} elemento{s} detectado{s}",
        "batch_import.to_choose": "ℹ️ Destino a elegir",
        "batch_import.detected": "✓ Detectado: {label}",
        "batch_import.manual": "Destino elegido manualmente",
        "batch_import.import_button": "Importar los {count} elemento{s}",
        "batch_import.imported": "{count} elemento{s} importado{s}",
        "batch_import.failed": "Algunos elementos fallaron: {names}",
        "batch_import.destination_tooltip": "Destino real dentro de esta categoría (vacío = la propia categoría)",
        "batch_import.choose_category": "Elegir una categoría",
        "batch_import.choose_destination": "Elegir un destino",
        "batch_import.choose_weapon": "Elegir un arma",
        "batch_import.no_sublevel": "Sin subnivel — la categoría es el destino",
        "batch_import.new_destination": "+ Nuevo destino",
        "batch_import.new_destination_title": "Nuevo destino",
        "batch_import.new_destination_prompt": "Nombre del nuevo destino:",
        "batch_import.new_destination_tooltip": "Crear un nuevo destino en esta categoría (acción explícita)",
        "profiles.import": "Importar un perfil",
        "profiles.import_tooltip": "Importar un perfil (.zip)",
        "profiles.import_filter": "Perfil RCM (*.zip *.rcmprofile);;Todos los archivos (*)",
        "profiles.conflict_title": "El perfil ya existe",
        "profiles.conflict_text": "Ya existe un perfil « {name} ». ¿Qué quieres hacer?",
        "profiles.conflict_replace": "Reemplazar",
        "profiles.conflict_copy": "Crear una copia",
    },
    "de": {
        "batch_import.title": "Mehrere Elemente importieren",
        "batch_import.count": "{count} Element{e} erkannt",
        "batch_import.to_choose": "ℹ️ Ziel auswählen",
        "batch_import.detected": "✓ Erkannt: {label}",
        "batch_import.manual": "Ziel manuell gewählt",
        "batch_import.import_button": "Die {count} Element{e} importieren",
        "batch_import.imported": "{count} Element{e} importiert",
        "batch_import.failed": "Einige Elemente fehlgeschlagen: {names}",
        "batch_import.destination_tooltip": "Reales Ziel in dieser Kategorie (leer = die Kategorie selbst)",
        "batch_import.choose_category": "Kategorie wählen",
        "batch_import.choose_destination": "Ziel wählen",
        "batch_import.choose_weapon": "Waffe wählen",
        "batch_import.no_sublevel": "Keine Unterebene — die Kategorie ist das Ziel",
        "batch_import.new_destination": "+ Neues Ziel",
        "batch_import.new_destination_title": "Neues Ziel",
        "batch_import.new_destination_prompt": "Name des neuen Ziels:",
        "batch_import.new_destination_tooltip": "Ein neues Ziel in dieser Kategorie erstellen (explizite Aktion)",
        "profiles.import": "Profil importieren",
        "profiles.import_tooltip": "Ein Profil importieren (.zip)",
        "profiles.import_filter": "RCM-Profil (*.zip *.rcmprofile);;Alle Dateien (*)",
        "profiles.conflict_title": "Profil existiert bereits",
        "profiles.conflict_text": "Ein Profil « {name} » existiert bereits. Was möchten Sie tun?",
        "profiles.conflict_replace": "Ersetzen",
        "profiles.conflict_copy": "Kopie erstellen",
    },
    "it": {
        "batch_import.title": "Importa più elementi",
        "batch_import.count": "{count} elemento{i} rilevato{i}",
        "batch_import.to_choose": "ℹ️ Destinazione da scegliere",
        "batch_import.detected": "✓ Rilevato: {label}",
        "batch_import.manual": "Destinazione scelta manualmente",
        "batch_import.import_button": "Importa {count} elemento{i}",
        "batch_import.imported": "{count} elemento{i} importato{i}",
        "batch_import.failed": "Alcuni elementi non riusciti: {names}",
        "batch_import.destination_tooltip": "Destinazione reale in questa categoria (vuota = la categoria stessa)",
        "batch_import.choose_category": "Scegli una categoria",
        "batch_import.choose_destination": "Scegli una destinazione",
        "batch_import.choose_weapon": "Scegli un'arma",
        "batch_import.no_sublevel": "Nessun sottolivello — la categoria è la destinazione",
        "batch_import.new_destination": "+ Nuova destinazione",
        "batch_import.new_destination_title": "Nuova destinazione",
        "batch_import.new_destination_prompt": "Nome della nuova destinazione:",
        "batch_import.new_destination_tooltip": "Crea una nuova destinazione in questa categoria (azione esplicita)",
        "profiles.import": "Importa un profilo",
        "profiles.import_tooltip": "Importa un profilo (.zip)",
        "profiles.import_filter": "Profilo RCM (*.zip *.rcmprofile);;Tutti i file (*)",
        "profiles.conflict_title": "Il profilo esiste già",
        "profiles.conflict_text": "Esiste già un profilo « {name} ». Cosa vuoi fare?",
        "profiles.conflict_replace": "Sostituisci",
        "profiles.conflict_copy": "Crea una copia",
    },
    "pt": {
        "batch_import.title": "Importar vários elementos",
        "batch_import.count": "{count} elemento{s} detectado{s}",
        "batch_import.to_choose": "ℹ️ Destino a escolher",
        "batch_import.detected": "✓ Detectado: {label}",
        "batch_import.manual": "Destino escolhido manualmente",
        "batch_import.import_button": "Importar os {count} elemento{s}",
        "batch_import.imported": "{count} elemento{s} importado{s}",
        "batch_import.failed": "Alguns elementos falharam: {names}",
        "batch_import.destination_tooltip": "Destino real dentro desta categoria (vazio = a própria categoria)",
        "batch_import.choose_category": "Escolher uma categoria",
        "batch_import.choose_destination": "Escolher um destino",
        "batch_import.choose_weapon": "Escolher uma arma",
        "batch_import.no_sublevel": "Sem subnível — a categoria é o destino",
        "batch_import.new_destination": "+ Novo destino",
        "batch_import.new_destination_title": "Novo destino",
        "batch_import.new_destination_prompt": "Nome do novo destino:",
        "batch_import.new_destination_tooltip": "Criar um novo destino nesta categoria (ação explícita)",
        "profiles.import": "Importar um perfil",
        "profiles.import_tooltip": "Importar um perfil (.zip)",
        "profiles.import_filter": "Perfil RCM (*.zip *.rcmprofile);;Todos os arquivos (*)",
        "profiles.conflict_title": "O perfil já existe",
        "profiles.conflict_text": "Já existe um perfil « {name} ». O que você quer fazer?",
        "profiles.conflict_replace": "Substituir",
        "profiles.conflict_copy": "Criar uma cópia",
    },
    "nl": {
        "batch_import.title": "Meerdere elementen importeren",
        "batch_import.count": "{count} element(en) gedetecteerd",
        "batch_import.to_choose": "ℹ️ Bestemming kiezen",
        "batch_import.detected": "✓ Gedetecteerd: {label}",
        "batch_import.manual": "Bestemming handmatig gekozen",
        "batch_import.import_button": "De {count} element(en) importeren",
        "batch_import.imported": "{count} element(en) geïmporteerd",
        "batch_import.failed": "Sommige elementen mislukt: {names}",
        "batch_import.destination_tooltip": "Echt doel binnen deze categorie (leeg = de categorie zelf)",
        "batch_import.choose_category": "Kies een categorie",
        "batch_import.choose_destination": "Kies een bestemming",
        "batch_import.choose_weapon": "Kies een wapen",
        "batch_import.no_sublevel": "Geen subniveau — de categorie is de bestemming",
        "batch_import.new_destination": "+ Nieuwe bestemming",
        "batch_import.new_destination_title": "Nieuwe bestemming",
        "batch_import.new_destination_prompt": "Naam van de nieuwe bestemming:",
        "batch_import.new_destination_tooltip": "Een nieuwe bestemming in deze categorie maken (expliciete actie)",
        "profiles.import": "Profiel importeren",
        "profiles.import_tooltip": "Een profiel importeren (.zip)",
        "profiles.import_filter": "RCM-profiel (*.zip *.rcmprofile);;Alle bestanden (*)",
        "profiles.conflict_title": "Profiel bestaat al",
        "profiles.conflict_text": "Er bestaat al een profiel « {name} ». Wat wil je doen?",
        "profiles.conflict_replace": "Vervangen",
        "profiles.conflict_copy": "Kopie maken",
    },
    "pl": {
        "batch_import.title": "Importuj wiele elementów",
        "batch_import.count": "Wykryto {count} element(y/ów)",
        "batch_import.to_choose": "ℹ️ Wybierz miejsce docelowe",
        "batch_import.detected": "✓ Wykryto: {label}",
        "batch_import.manual": "Miejsce wybrane ręcznie",
        "batch_import.import_button": "Importuj {count} element(y/ów)",
        "batch_import.imported": "Zaimportowano {count} element(y/ów)",
        "batch_import.failed": "Niektóre elementy się nie powiodły: {names}",
        "batch_import.destination_tooltip": "Rzeczywiste miejsce w tej kategorii (puste = sama kategoria)",
        "batch_import.choose_category": "Wybierz kategorię",
        "batch_import.choose_destination": "Wybierz miejsce docelowe",
        "batch_import.choose_weapon": "Wybierz broń",
        "batch_import.no_sublevel": "Brak podpoziomu — kategoria jest miejscem docelowym",
        "batch_import.new_destination": "+ Nowe miejsce docelowe",
        "batch_import.new_destination_title": "Nowe miejsce docelowe",
        "batch_import.new_destination_prompt": "Nazwa nowego miejsca docelowego:",
        "batch_import.new_destination_tooltip": "Utwórz nowe miejsce docelowe w tej kategorii (jawna akcja)",
        "profiles.import": "Importuj profil",
        "profiles.import_tooltip": "Importuj profil (.zip)",
        "profiles.import_filter": "Profil RCM (*.zip *.rcmprofile);;Wszystkie pliki (*)",
        "profiles.conflict_title": "Profil już istnieje",
        "profiles.conflict_text": "Profil « {name} » już istnieje. Co chcesz zrobić?",
        "profiles.conflict_replace": "Zastąp",
        "profiles.conflict_copy": "Utwórz kopię",
    },
    "ru": {
        "batch_import.title": "Импортировать несколько элементов",
        "batch_import.count": "Обнаружено: {count} элемент(ов)",
        "batch_import.to_choose": "ℹ️ Выберите место назначения",
        "batch_import.detected": "✓ Обнаружено: {label}",
        "batch_import.manual": "Место выбрано вручную",
        "batch_import.import_button": "Импортировать {count} элемент(ов)",
        "batch_import.imported": "Импортировано: {count} элемент(ов)",
        "batch_import.failed": "Некоторые элементы не удалось импортировать: {names}",
        "batch_import.destination_tooltip": "Реальный путь в этой категории (пусто = сама категория)",
        "batch_import.choose_category": "Выберите категорию",
        "batch_import.choose_destination": "Выберите место назначения",
        "batch_import.choose_weapon": "Выберите оружие",
        "batch_import.no_sublevel": "Нет подуровня — категория и есть назначение",
        "batch_import.new_destination": "+ Новое место назначения",
        "batch_import.new_destination_title": "Новое место назначения",
        "batch_import.new_destination_prompt": "Название нового места назначения:",
        "batch_import.new_destination_tooltip": "Создать новое место назначения в этой категории (явное действие)",
        "profiles.import": "Импортировать профиль",
        "profiles.import_tooltip": "Импортировать профиль (.zip)",
        "profiles.import_filter": "Профиль RCM (*.zip *.rcmprofile);;Все файлы (*)",
        "profiles.conflict_title": "Профиль уже существует",
        "profiles.conflict_text": "Профиль « {name} » уже существует. Что вы хотите сделать?",
        "profiles.conflict_replace": "Заменить",
        "profiles.conflict_copy": "Создать копию",
    },
    "tr": {
        "batch_import.title": "Birden fazla öğeyi içe aktar",
        "batch_import.count": "{count} öğe algılandı",
        "batch_import.to_choose": "ℹ️ Seçilecek hedef",
        "batch_import.detected": "✓ Algılandı: {label}",
        "batch_import.manual": "Hedef elle seçildi",
        "batch_import.import_button": "{count} öğeyi içe aktar",
        "batch_import.imported": "{count} öğe içe aktarıldı",
        "batch_import.failed": "Bazı öğeler başarısız oldu: {names}",
        "batch_import.destination_tooltip": "Bu kategorideki gerçek hedef (boş = kategorinin kendisi)",
        "batch_import.choose_category": "Bir kategori seçin",
        "batch_import.choose_destination": "Bir hedef seçin",
        "batch_import.choose_weapon": "Bir silah seçin",
        "batch_import.no_sublevel": "Alt düzey yok — kategori hedefin kendisidir",
        "batch_import.new_destination": "+ Yeni hedef",
        "batch_import.new_destination_title": "Yeni hedef",
        "batch_import.new_destination_prompt": "Yeni hedefin adı:",
        "batch_import.new_destination_tooltip": "Bu kategoride yeni bir hedef oluştur (açık eylem)",
        "profiles.import": "Profil içe aktar",
        "profiles.import_tooltip": "Bir profil içe aktar (.zip)",
        "profiles.import_filter": "RCM Profili (*.zip *.rcmprofile);;Tüm dosyalar (*)",
        "profiles.conflict_title": "Profil zaten var",
        "profiles.conflict_text": "« {name} » adında bir profil zaten var. Ne yapmak istersiniz?",
        "profiles.conflict_replace": "Değiştir",
        "profiles.conflict_copy": "Kopya oluştur",
    },
}

for code, mapping in TRANS.items():
    path = f"app/i18n/translations/{code}.json"
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    for dotted, value in mapping.items():
        parts = dotted.split(".")
        node = data
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = value
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
        f.write("\n")
    print(f"{code}: ok")
