"""Add the v1.3.4 translation keys to every language file (parity)."""
from __future__ import annotations

import json

TRANS = {
    "fr": {
        "deps.ignored": "✓ {name} (validée — non bloquante)",
        "profiles.detected_note": "Configurations détectées dans Fleasion : {count}",
        "validation.validate": "✓ Valider",
        "validation.validate_tooltip": "Confirmer que cette configuration fonctionne malgré les dépendances signalées",
        "validation.title": "Validation de la configuration",
        "validation.question": "Cette configuration fonctionne-t-elle correctement malgré les dépendances actuellement signalées ?",
        "validation.yes": "✓ Oui, elle fonctionne",
        "validation.no": "✕ Non",
        "validation.validated": "✓ Validée",
        "validation.validated_note": "Dépendances signalées ignorées pour cette configuration (validation utilisateur).",
        "validation.reset": "Réinitialiser",
        "validation.reset_tooltip": "Réinitialiser la validation (les dépendances signalées redeviennent bloquantes)",
        "toast.validated": "✓ Configuration validée — les dépendances signalées ne sont plus bloquantes.",
        "toast.validation_reset": "Validation réinitialisée.",
        "toast.fleasion_folder_inaccessible": "Dossier actif de Fleasion inaccessible.",
    },
    "en": {
        "deps.ignored": "✓ {name} (validated — not blocking)",
        "profiles.detected_note": "Configurations detected in Fleasion: {count}",
        "validation.validate": "✓ Validate",
        "validation.validate_tooltip": "Confirm that this configuration works despite the flagged dependencies",
        "validation.title": "Configuration validation",
        "validation.question": "Does this configuration work correctly despite the currently flagged dependencies?",
        "validation.yes": "✓ Yes, it works",
        "validation.no": "✕ No",
        "validation.validated": "✓ Validated",
        "validation.validated_note": "Flagged dependencies are ignored for this configuration (user validation).",
        "validation.reset": "Reset",
        "validation.reset_tooltip": "Reset the validation (flagged dependencies become blocking again)",
        "toast.validated": "✓ Configuration validated — flagged dependencies are no longer blocking.",
        "toast.validation_reset": "Validation reset.",
        "toast.fleasion_folder_inaccessible": "Fleasion active folder is inaccessible.",
    },
    "es": {
        "deps.ignored": "✓ {name} (validada — no bloqueante)",
        "profiles.detected_note": "Configuraciones detectadas en Fleasion: {count}",
        "validation.validate": "✓ Validar",
        "validation.validate_tooltip": "Confirmar que esta configuración funciona a pesar de las dependencias señaladas",
        "validation.title": "Validación de la configuración",
        "validation.question": "¿Esta configuración funciona correctamente a pesar de las dependencias actualmente señaladas?",
        "validation.yes": "✓ Sí, funciona",
        "validation.no": "✕ No",
        "validation.validated": "✓ Validada",
        "validation.validated_note": "Dependencias señaladas ignoradas para esta configuración (validación del usuario).",
        "validation.reset": "Restablecer",
        "validation.reset_tooltip": "Restablecer la validación (las dependencias señaladas vuelven a ser bloqueantes)",
        "toast.validated": "✓ Configuración validada: las dependencias señaladas ya no son bloqueantes.",
        "toast.validation_reset": "Validación restablecida.",
        "toast.fleasion_folder_inaccessible": "La carpeta activa de Fleasion es inaccesible.",
    },
    "de": {
        "deps.ignored": "✓ {name} (validiert — nicht blockierend)",
        "profiles.detected_note": "In Fleasion erkannte Konfigurationen: {count}",
        "validation.validate": "✓ Validieren",
        "validation.validate_tooltip": "Bestätigen, dass diese Konfiguration trotz der gemeldeten Abhängigkeiten funktioniert",
        "validation.title": "Validierung der Konfiguration",
        "validation.question": "Funktioniert diese Konfiguration trotz der derzeit gemeldeten Abhängigkeiten korrekt?",
        "validation.yes": "✓ Ja, sie funktioniert",
        "validation.no": "✕ Nein",
        "validation.validated": "✓ Validierte",
        "validation.validated_note": "Gemeldete Abhängigkeiten werden für diese Konfiguration ignoriert (Benutzervalidierung).",
        "validation.reset": "Zurücksetzen",
        "validation.reset_tooltip": "Validierung zurücksetzen (gemeldete Abhängigkeiten werden wieder blockierend)",
        "toast.validated": "✓ Konfiguration validiert — gemeldete Abhängigkeiten blockieren nicht mehr.",
        "toast.validation_reset": "Validierung zurückgesetzt.",
        "toast.fleasion_folder_inaccessible": "Aktiver Fleasion-Ordner nicht zugänglich.",
    },
    "it": {
        "deps.ignored": "✓ {name} (validata — non bloccante)",
        "profiles.detected_note": "Configurazioni rilevate in Fleasion: {count}",
        "validation.validate": "✓ Valida",
        "validation.validate_tooltip": "Conferma che questa configurazione funziona nonostante le dipendenze segnalate",
        "validation.title": "Validazione della configurazione",
        "validation.question": "Questa configurazione funziona correttamente nonostante le dipendenze attualmente segnalate?",
        "validation.yes": "✓ Sì, funziona",
        "validation.no": "✕ No",
        "validation.validated": "✓ Validata",
        "validation.validated_note": "Dipendenze segnalate ignorate per questa configurazione (validazione utente).",
        "validation.reset": "Reimposta",
        "validation.reset_tooltip": "Reimposta la validazione (le dipendenze segnalate tornano bloccanti)",
        "toast.validated": "✓ Configurazione validata: le dipendenze segnalate non sono più bloccanti.",
        "toast.validation_reset": "Validazione reimpostata.",
        "toast.fleasion_folder_inaccessible": "Cartella attiva di Fleasion non accessibile.",
    },
    "nl": {
        "deps.ignored": "✓ {name} (gevalideerd — niet blokkerend)",
        "profiles.detected_note": "Configuraties gedetecteerd in Fleasion: {count}",
        "validation.validate": "✓ Valideren",
        "validation.validate_tooltip": "Bevestig dat deze configuratie werkt ondanks de gemarkeerde afhankelijkheden",
        "validation.title": "Configuratievalidatie",
        "validation.question": "Werkt deze configuratie correct ondanks de momenteel gemarkeerde afhankelijkheden?",
        "validation.yes": "✓ Ja, hij werkt",
        "validation.no": "✕ Nee",
        "validation.validated": "✓ Gevalideerd",
        "validation.validated_note": "Gemarkeerde afhankelijkheden worden genegeerd voor deze configuratie (gebruikersvalidatie).",
        "validation.reset": "Resetten",
        "validation.reset_tooltip": "Validatie resetten (gemarkeerde afhankelijkheden worden weer blokkerend)",
        "toast.validated": "✓ Configuratie gevalideerd — gemarkeerde afhankelijkheden blokkeren niet meer.",
        "toast.validation_reset": "Validatie gereset.",
        "toast.fleasion_folder_inaccessible": "Actieve Fleasion-map is niet toegankelijk.",
    },
    "pl": {
        "deps.ignored": "✓ {name} (zweryfikowana — nie blokuje)",
        "profiles.detected_note": "Konfiguracje wykryte w Fleasion: {count}",
        "validation.validate": "✓ Zweryfikuj",
        "validation.validate_tooltip": "Potwierdź, że ta konfiguracja działa pomimo oznaczonych zależności",
        "validation.title": "Weryfikacja konfiguracji",
        "validation.question": "Czy ta konfiguracja działa poprawnie pomimo aktualnie oznaczonych zależności?",
        "validation.yes": "✓ Tak, działa",
        "validation.no": "✕ Nie",
        "validation.validated": "✓ Zweryfikowana",
        "validation.validated_note": "Oznaczone zależności są ignorowane dla tej konfiguracji (weryfikacja użytkownika).",
        "validation.reset": "Resetuj",
        "validation.reset_tooltip": "Zresetuj weryfikację (oznaczone zależności znów blokują)",
        "toast.validated": "✓ Konfiguracja zweryfikowana — oznaczone zależności już nie blokują.",
        "toast.validation_reset": "Weryfikacja zresetowana.",
        "toast.fleasion_folder_inaccessible": "Aktywny folder Fleasion jest niedostępny.",
    },
    "pt": {
        "deps.ignored": "✓ {name} (validada — não bloqueante)",
        "profiles.detected_note": "Configurações detectadas no Fleasion: {count}",
        "validation.validate": "✓ Validar",
        "validation.validate_tooltip": "Confirmar que esta configuração funciona apesar das dependências sinalizadas",
        "validation.title": "Validação da configuração",
        "validation.question": "Esta configuração funciona corretamente apesar das dependências atualmente sinalizadas?",
        "validation.yes": "✓ Sim, funciona",
        "validation.no": "✕ Não",
        "validation.validated": "✓ Validada",
        "validation.validated_note": "Dependências sinalizadas ignoradas para esta configuração (validação do usuário).",
        "validation.reset": "Redefinir",
        "validation.reset_tooltip": "Redefinir a validação (as dependências sinalizadas voltam a bloquear)",
        "toast.validated": "✓ Configuração validada — as dependências sinalizadas deixaram de bloquear.",
        "toast.validation_reset": "Validação redefinida.",
        "toast.fleasion_folder_inaccessible": "Pasta ativa do Fleasion inacessível.",
    },
    "ru": {
        "deps.ignored": "✓ {name} (подтверждено — не блокирует)",
        "profiles.detected_note": "Конфигураций обнаружено в Fleasion: {count}",
        "validation.validate": "✓ Подтвердить",
        "validation.validate_tooltip": "Подтвердить, что эта конфигурация работает несмотря на отмеченные зависимости",
        "validation.title": "Подтверждение конфигурации",
        "validation.question": "Работает ли эта конфигурация корректно несмотря на отмеченные зависимости?",
        "validation.yes": "✓ Да, работает",
        "validation.no": "✕ Нет",
        "validation.validated": "✓ Подтверждено",
        "validation.validated_note": "Отмеченные зависимости игнорируются для этой конфигурации (подтверждение пользователем).",
        "validation.reset": "Сбросить",
        "validation.reset_tooltip": "Сбросить подтверждение (отмеченные зависимости снова станут блокирующими)",
        "toast.validated": "✓ Конфигурация подтверждена — отмеченные зависимости больше не блокируют.",
        "toast.validation_reset": "Подтверждение сброшено.",
        "toast.fleasion_folder_inaccessible": "Активная папка Fleasion недоступна.",
    },
    "tr": {
        "deps.ignored": "✓ {name} (doğrulandı — engellemiyor)",
        "profiles.detected_note": "Fleasion'da algılanan yapılandırmalar: {count}",
        "validation.validate": "✓ Doğrula",
        "validation.validate_tooltip": "Bu yapılandırmanın işaretli bağımlılıklara rağmen çalıştığını onayla",
        "validation.title": "Yapılandırma doğrulaması",
        "validation.question": "Bu yapılandırma, şu anda işaretlenen bağımlılıklara rağmen doğru şekilde çalışıyor mu?",
        "validation.yes": "✓ Evet, çalışıyor",
        "validation.no": "✕ Hayır",
        "validation.validated": "✓ Doğrulandı",
        "validation.validated_note": "İşaretli bağımlılıklar bu yapılandırma için yok sayılır (kullanıcı doğrulaması).",
        "validation.reset": "Sıfırla",
        "validation.reset_tooltip": "Doğrulamayı sıfırla (işaretli bağımlılıklar tekrar engelleyici olur)",
        "toast.validated": "✓ Yapılandırma doğrulandı — işaretli bağımlılıklar artık engellemiyor.",
        "toast.validation_reset": "Doğrulama sıfırlandı.",
        "toast.fleasion_folder_inaccessible": "Fleasion aktif klasörü erişilemez.",
    },
}

for code, mapping in TRANS.items():
    path = f"app/i18n/translations/{code}.json"
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    for dotted, value in mapping.items():
        parts = dotted.split(".")
        node = data
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = value
    if "profiles" in data and "capture_note_saved" in data["profiles"]:
        del data["profiles"]["capture_note_saved"]
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"{code}: ok")
