"""One-shot script: add every v1.3.0 key to the 10 translation files.

Run from the project root:  python tools/add_v130_keys.py
Safe to re-run (existing keys are never overwritten).
"""

from __future__ import annotations

import json
from pathlib import Path

TRANS = Path("app/i18n/translations")

# ---------------------------------------------------------------------- #
# New v1.3.0 keys, one nested dict per language (same keys everywhere).
# ---------------------------------------------------------------------- #
_BASE = {
    "search": {
        "page_title": "Search",
        "page_placeholder": "Search for a configuration…",
        "clear": "Clear",
        "clear_tooltip": "Clear the search",
        "recents": "Recents",
        "recents_subtitle": "Recently used configurations",
        "recent_item": "Recent",
        "no_recents": "No recent configurations yet.",
    },
    "favorites": {
        "filter_all": "All",
        "filter_only": "Favorites",
        "filter_excluded": "Not favorites",
    },
    "card": {
        "favorite_add": "Add to favorites",
        "favorite_remove": "Remove from favorites",
        "status_ready": "Ready",
        "status_incomplete": "Incomplete",
        "status_error": "Error",
        "status_active": "Active",
    },
    "config": {
        "verify": "VERIFY",
        "verify_tooltip": "Verify the configuration (JSON, dependencies, files, category)",
    },
    "verify": {
        "valid": "Valid configuration",
        "incomplete": "Incomplete configuration",
        "deps_ok": "Dependencies present",
        "usable_note": "The configuration cannot work correctly until these files are present.",
        "missing_dependency": "Missing {kind}: {name}",
        "missing_file": "Missing file: {name}",
        "invalid_category": "Category not found",
        "no_json": "No JSON file in this configuration.",
    },
    "repair": {
        "button": "Repair",
        "button_tooltip": "Try to repair the missing dependencies",
        "action_copy": "Copy {name}",
        "possible": "Repair possible: {count} file{s} to copy.",
        "impossible": "Cannot repair automatically.\n\nMissing file(s):\n{files}",
        "nothing": "Nothing to repair.",
        "source_missing": "Source not found: {name}",
        "copy_failed": "Cannot copy {name}: {detail}",
        "confirm_text": "The application will copy the missing files next to the configuration.",
        "do": "Repair",
        "partial": "Partial repair:\n{errors}",
    },
    "profiles": {
        "title": "Profiles",
        "subtitle": "Save a group of configurations and restore it in one click.",
        "create": "Create a profile",
        "edit": "Edit",
        "delete": "Delete",
        "apply": "Apply",
        "export": "Export",
        "import": "Import",
        "import_tooltip": "Import a profile (.rcmprofile)",
        "no_profiles": "No profiles yet — create the first one.",
        "no_description": "No description",
        "count_one": "1 configuration",
        "count_many": "{count} configurations",
        "status_ready": "Ready",
        "status_missing": "{count} configuration(s) missing",
        "name": "Name",
        "name_placeholder": "e.g. Tryhard",
        "description": "Description",
        "description_placeholder": "Optional",
        "capture_note": "Profile configurations (pre-checked: active in Fleasion)",
        "create_title": "New profile",
        "edit_title": "Edit profile",
        "export_dialog": "Export profile",
        "import_dialog": "Import a profile",
        "name_required": "The profile name is required.",
        "already_exists": "A profile « {name} » already exists.",
        "not_found": "Profile not found: {name}",
        "import_invalid": "Invalid profile file: {path}",
    },
    "theme": {
        "dark": "Dark",
        "light": "Light",
        "blue": "Blue",
        "red": "Red",
        "green": "Green",
        "purple": "Purple",
        "midnight": "Midnight",
        "custom": "Custom",
        "custom_title": "Custom theme",
        "primary": "Primary color",
        "secondary": "Secondary color",
        "accent": "Accent",
        "background": "Background",
        "gradient": "Gradient",
        "gradient_angle": "Gradient angle",
        "pick_color": "Pick a color",
    },
    "settings": {
        "theme": "Theme",
        "shortcuts_title": "Keyboard shortcuts",
    },
    "shortcuts": {
        "open_search": "Open search",
        "go_home": "Go back home",
        "verify_config": "Verify the selected configuration",
        "toggle_config": "Activate / deactivate the selected configuration",
    },
    "detection": {
        "obj": "OBJ",
        "mp3": "MP3",
        "deps": "{deps}",
        "deps_label": "Detected dependencies: {deps}",
    },
    "toast": {
        "favorite_added": "Added to favorites",
        "favorite_removed": "Removed from favorites",
        "verify_ok": "Valid configuration",
        "verify_incomplete": "Incomplete configuration",
        "repair_ok": "Configuration repaired and verified",
        "repair_not_fixed": "The configuration is still incomplete",
        "profile_created": "Profile « {name} » created",
        "profile_updated": "Profile « {name} » updated",
        "profile_deleted": "Profile « {name} » deleted",
        "profile_applied": "Profile « {name} » applied",
        "profile_partial": "Profile « {name} » partially applied — failures: {failed}",
        "profile_nothing_applied": "No configuration of the profile could be applied",
        "profile_exported": "Profile exported: {path}",
        "profile_imported": "Profile « {name} » imported",
        "theme_applied": "Theme applied",
        "item_not_found": "Item not found",
    },
    "confirm": {
        "profile_delete_title": "Delete the profile",
        "profile_delete_text": "Delete the profile « {name} »?",
        "profile_delete_info": "The library configurations are not touched.",
        "profile_missing_title": "Missing configurations",
        "profile_missing_text_one": "The profile « {name} » contains 1 missing configuration.",
        "profile_missing_text_many": "The profile « {name} » contains {count} missing configurations.",
        "profile_missing_info": "Missing configurations:\n{files}\n\nThe other configurations can still be applied.",
        "profile_continue": "Continue",
    },
}


def _fr() -> dict:
    return {
        "search": {
            "page_title": "Rechercher",
            "page_placeholder": "Rechercher une configuration…",
            "clear": "Effacer",
            "clear_tooltip": "Effacer la recherche",
            "recents": "Récents",
            "recents_subtitle": "Configurations récemment consultées",
            "recent_item": "Récent",
            "no_recents": "Aucune configuration récente pour l'instant.",
        },
        "favorites": {
            "filter_all": "Toutes",
            "filter_only": "Favoris",
            "filter_excluded": "Non favoris",
        },
        "card": {
            "favorite_add": "Ajouter aux favoris",
            "favorite_remove": "Retirer des favoris",
            "status_ready": "Prête",
            "status_incomplete": "Incomplète",
            "status_error": "Erreur",
            "status_active": "Active",
        },
        "config": {
            "verify": "VÉRIFIER",
            "verify_tooltip": "Vérifier la configuration (JSON, dépendances, fichiers, catégorie)",
        },
        "verify": {
            "valid": "✓ Configuration valide",
            "incomplete": "⚠ Configuration incomplète",
            "deps_ok": "Dépendances présentes",
            "usable_note": "La configuration ne pourra pas fonctionner correctement tant que ces fichiers ne sont pas présents.",
            "missing_dependency": "{kind} manquant : {name}",
            "missing_file": "Fichier manquant : {name}",
            "invalid_category": "Catégorie introuvable",
            "no_json": "Aucun fichier JSON dans cette configuration.",
        },
        "repair": {
            "button": "Réparer",
            "button_tooltip": "Tenter de réparer les dépendances manquantes",
            "action_copy": "Copier {name}",
            "possible": "Réparation possible : {count} fichier{s} à copier.",
            "impossible": "Impossible de réparer automatiquement.\n\nFichier(s) manquant(s) :\n{files}",
            "nothing": "Rien à réparer.",
            "source_missing": "Source introuvable : {name}",
            "copy_failed": "Copie impossible de {name} : {detail}",
            "confirm_text": "L'application va copier les fichiers manquants à côté de la configuration.",
            "do": "Réparer",
            "partial": "Réparation partielle :\n{errors}",
        },
        "profiles": {
            "title": "Profils",
            "subtitle": "Sauvegardez un groupe de configurations et restaurez-le en un clic.",
            "create": "Créer un profil",
            "edit": "Modifier",
            "delete": "Supprimer",
            "apply": "Appliquer",
            "export": "Exporter",
            "import": "Importer",
            "import_tooltip": "Importer un profil (.rcmprofile)",
            "no_profiles": "Aucun profil pour l'instant — créez le premier.",
            "no_description": "Aucune description",
            "count_one": "1 configuration",
            "count_many": "{count} configurations",
            "status_ready": "Prêt",
            "status_missing": "{count} configuration(s) introuvable(s)",
            "name": "Nom",
            "name_placeholder": "Ex. Tryhard",
            "description": "Description",
            "description_placeholder": "Optionnel",
            "capture_note": "Configurations du profil (pré-cochées : actives dans Fleasion)",
            "create_title": "Nouveau profil",
            "edit_title": "Modifier le profil",
            "export_dialog": "Exporter le profil",
            "import_dialog": "Importer un profil",
            "name_required": "Le nom du profil est requis.",
            "already_exists": "Un profil « {name} » existe déjà.",
            "not_found": "Profil introuvable : {name}",
            "import_invalid": "Fichier de profil invalide : {path}",
        },
        "theme": {
            "dark": "Sombre",
            "light": "Clair",
            "blue": "Bleu",
            "red": "Rouge",
            "green": "Vert",
            "purple": "Violet",
            "midnight": "Minuit",
            "custom": "Personnalisé",
            "custom_title": "Thème personnalisé",
            "primary": "Couleur principale",
            "secondary": "Couleur secondaire",
            "accent": "Accent",
            "background": "Fond",
            "gradient": "Dégradé",
            "gradient_angle": "Angle du dégradé",
            "pick_color": "Choisir une couleur",
        },
        "settings": {
            "theme": "Thème",
            "shortcuts_title": "Raccourcis clavier",
        },
        "shortcuts": {
            "open_search": "Ouvrir la recherche",
            "go_home": "Revenir à l'accueil",
            "verify_config": "Vérifier la configuration sélectionnée",
            "toggle_config": "Activer / désactiver la configuration sélectionnée",
        },
        "detection": {
            "obj": "OBJ",
            "mp3": "MP3",
            "deps": "{deps}",
            "deps_label": "Dépendances détectées : {deps}",
        },
        "toast": {
            "favorite_added": "Ajouté aux favoris",
            "favorite_removed": "Retiré des favoris",
            "verify_ok": "Configuration valide",
            "verify_incomplete": "Configuration incomplète",
            "repair_ok": "Configuration réparée et vérifiée",
            "repair_not_fixed": "La configuration est toujours incomplète",
            "profile_created": "Profil « {name} » créé",
            "profile_updated": "Profil « {name} » mis à jour",
            "profile_deleted": "Profil « {name} » supprimé",
            "profile_applied": "Profil « {name} » appliqué",
            "profile_partial": "Profil « {name} » partiellement appliqué — échecs : {failed}",
            "profile_nothing_applied": "Aucune configuration du profil n'a pu être appliquée",
            "profile_exported": "Profil exporté : {path}",
            "profile_imported": "Profil « {name} » importé",
            "theme_applied": "Thème appliqué",
            "item_not_found": "Élément introuvable",
        },
        "confirm": {
            "profile_delete_title": "Supprimer le profil",
            "profile_delete_text": "Supprimer le profil « {name} » ?",
            "profile_delete_info": "Les configurations de la bibliothèque ne sont pas touchées.",
            "profile_missing_title": "Configurations introuvables",
            "profile_missing_text_one": "Le profil « {name} » contient 1 configuration introuvable.",
            "profile_missing_text_many": "Le profil « {name} » contient {count} configurations introuvables.",
            "profile_missing_info": "Configurations manquantes :\n{files}\n\nLes autres configurations peuvent être appliquées.",
            "profile_continue": "Continuer",
        },
    }


# ---------------------------------------------------------------------- #
# Translations for the other languages: build from EN with a per-language
# patch of the user-facing strings.
# ---------------------------------------------------------------------- #
_LANG_PATCHES: dict[str, dict] = {
    "es": {
        "search": {
            "page_title": "Buscar",
            "page_placeholder": "Buscar una configuración…",
            "clear": "Borrar",
            "clear_tooltip": "Borrar la búsqueda",
            "recents": "Recientes",
            "recents_subtitle": "Configuraciones vistas recientemente",
            "recent_item": "Reciente",
            "no_recents": "Aún no hay configuraciones recientes.",
        },
        "favorites": {
            "filter_all": "Todas",
            "filter_only": "Favoritas",
            "filter_excluded": "No favoritas",
        },
        "card": {
            "favorite_add": "Añadir a favoritos",
            "favorite_remove": "Quitar de favoritos",
            "status_ready": "Lista",
            "status_incomplete": "Incompleta",
            "status_error": "Error",
            "status_active": "Activa",
        },
        "config": {
            "verify": "VERIFICAR",
            "verify_tooltip": "Verificar la configuración (JSON, dependencias, archivos, categoría)",
        },
        "verify": {
            "valid": "✓ Configuración válida",
            "incomplete": "⚠ Configuración incompleta",
            "deps_ok": "Dependencias presentes",
            "usable_note": "La configuración no funcionará correctamente hasta que estos archivos estén presentes.",
            "missing_dependency": "Falta {kind}: {name}",
            "missing_file": "Archivo faltante: {name}",
            "invalid_category": "Categoría no encontrada",
            "no_json": "No hay archivos JSON en esta configuración.",
        },
        "repair": {
            "button": "Reparar",
            "button_tooltip": "Intentar reparar las dependencias faltantes",
            "action_copy": "Copiar {name}",
            "possible": "Reparación posible: {count} archivo{s} por copiar.",
            "impossible": "No se puede reparar automáticamente.\n\nArchivo(s) faltante(s):\n{files}",
            "nothing": "Nada que reparar.",
            "source_missing": "Origen no encontrado: {name}",
            "copy_failed": "No se pudo copiar {name}: {detail}",
            "confirm_text": "La aplicación copiará los archivos faltantes junto a la configuración.",
            "do": "Reparar",
            "partial": "Reparación parcial:\n{errors}",
        },
        "profiles": {
            "title": "Perfiles",
            "subtitle": "Guarda un grupo de configuraciones y restáuralo con un clic.",
            "create": "Crear perfil",
            "edit": "Editar",
            "delete": "Eliminar",
            "apply": "Aplicar",
            "export": "Exportar",
            "import": "Importar",
            "import_tooltip": "Importar un perfil (.rcmprofile)",
            "no_profiles": "Aún no hay perfiles — crea el primero.",
            "no_description": "Sin descripción",
            "count_one": "1 configuración",
            "count_many": "{count} configuraciones",
            "status_ready": "Listo",
            "status_missing": "{count} configuración(es) no encontrada(s)",
            "name": "Nombre",
            "name_placeholder": "p. ej. Tryhard",
            "description": "Descripción",
            "description_placeholder": "Opcional",
            "capture_note": "Configuraciones del perfil (premarcadas: activas en Fleasion)",
            "create_title": "Nuevo perfil",
            "edit_title": "Editar perfil",
            "export_dialog": "Exportar perfil",
            "import_dialog": "Importar un perfil",
            "name_required": "El nombre del perfil es obligatorio.",
            "already_exists": "Ya existe un perfil « {name} ».",
            "not_found": "Perfil no encontrado: {name}",
            "import_invalid": "Archivo de perfil no válido: {path}",
        },
        "theme": {
            "dark": "Oscuro",
            "light": "Claro",
            "blue": "Azul",
            "red": "Rojo",
            "green": "Verde",
            "purple": "Violeta",
            "midnight": "Medianoche",
            "custom": "Personalizado",
            "custom_title": "Tema personalizado",
            "primary": "Color principal",
            "secondary": "Color secundario",
            "accent": "Acento",
            "background": "Fondo",
            "gradient": "Degradado",
            "gradient_angle": "Ángulo del degradado",
            "pick_color": "Elegir un color",
        },
        "settings": {
            "theme": "Tema",
            "shortcuts_title": "Atajos de teclado",
        },
        "shortcuts": {
            "open_search": "Abrir la búsqueda",
            "go_home": "Volver al inicio",
            "verify_config": "Verificar la configuración seleccionada",
            "toggle_config": "Activar / desactivar la configuración seleccionada",
        },
        "detection": {
            "deps_label": "Dependencias detectadas: {deps}",
        },
        "toast": {
            "favorite_added": "Añadido a favoritos",
            "favorite_removed": "Quitado de favoritos",
            "verify_ok": "Configuración válida",
            "verify_incomplete": "Configuración incompleta",
            "repair_ok": "Configuración reparada y verificada",
            "repair_not_fixed": "La configuración sigue incompleta",
            "profile_created": "Perfil « {name} » creado",
            "profile_updated": "Perfil « {name} » actualizado",
            "profile_deleted": "Perfil « {name} » eliminado",
            "profile_applied": "Perfil « {name} » aplicado",
            "profile_partial": "Perfil « {name} » aplicado parcialmente — errores: {failed}",
            "profile_nothing_applied": "No se pudo aplicar ninguna configuración del perfil",
            "profile_exported": "Perfil exportado: {path}",
            "profile_imported": "Perfil « {name} » importado",
            "theme_applied": "Tema aplicado",
            "item_not_found": "Elemento no encontrado",
        },
        "confirm": {
            "profile_delete_title": "Eliminar el perfil",
            "profile_delete_text": "¿Eliminar el perfil « {name} »?",
            "profile_delete_info": "Las configuraciones de la biblioteca no se tocan.",
            "profile_missing_title": "Configuraciones no encontradas",
            "profile_missing_text_one": "El perfil « {name} » contiene 1 configuración no encontrada.",
            "profile_missing_text_many": "El perfil « {name} » contiene {count} configuraciones no encontradas.",
            "profile_missing_info": "Configuraciones faltantes:\n{files}\n\nLas demás configuraciones pueden aplicarse.",
            "profile_continue": "Continuar",
        },
    },
    "de": {
        "search": {
            "page_title": "Suchen",
            "page_placeholder": "Konfiguration suchen…",
            "clear": "Löschen",
            "clear_tooltip": "Suche löschen",
            "recents": "Zuletzt verwendet",
            "recents_subtitle": "Zuletzt verwendete Konfigurationen",
            "recent_item": "Zuletzt",
            "no_recents": "Noch keine zuletzt verwendeten Konfigurationen.",
        },
        "favorites": {
            "filter_all": "Alle",
            "filter_only": "Favoriten",
            "filter_excluded": "Keine Favoriten",
        },
        "card": {
            "favorite_add": "Zu Favoriten hinzufügen",
            "favorite_remove": "Aus Favoriten entfernen",
            "status_ready": "Bereit",
            "status_incomplete": "Unvollständig",
            "status_error": "Fehler",
            "status_active": "Aktiv",
        },
        "config": {
            "verify": "PRÜFEN",
            "verify_tooltip": "Konfiguration prüfen (JSON, Abhängigkeiten, Dateien, Kategorie)",
        },
        "verify": {
            "valid": "✓ Gültige Konfiguration",
            "incomplete": "⚠ Unvollständige Konfiguration",
            "deps_ok": "Abhängigkeiten vorhanden",
            "usable_note": "Die Konfiguration kann erst korrekt funktionieren, wenn diese Dateien vorhanden sind.",
            "missing_dependency": "{kind} fehlt: {name}",
            "missing_file": "Fehlende Datei: {name}",
            "invalid_category": "Kategorie nicht gefunden",
            "no_json": "Keine JSON-Datei in dieser Konfiguration.",
        },
        "repair": {
            "button": "Reparieren",
            "button_tooltip": "Fehlende Abhängigkeiten reparieren",
            "action_copy": "{name} kopieren",
            "possible": "Reparatur möglich: {count} Datei{s} zu kopieren.",
            "impossible": "Automatische Reparatur nicht möglich.\n\nFehlende Datei(en):\n{files}",
            "nothing": "Nichts zu reparieren.",
            "source_missing": "Quelle nicht gefunden: {name}",
            "copy_failed": "{name} kann nicht kopiert werden: {detail}",
            "confirm_text": "Die Anwendung kopiert die fehlenden Dateien neben die Konfiguration.",
            "do": "Reparieren",
            "partial": "Teilweise Reparatur:\n{errors}",
        },
        "profiles": {
            "title": "Profile",
            "subtitle": "Gruppe von Konfigurationen speichern und mit einem Klick wiederherstellen.",
            "create": "Profil erstellen",
            "edit": "Bearbeiten",
            "delete": "Löschen",
            "apply": "Anwenden",
            "export": "Exportieren",
            "import": "Importieren",
            "import_tooltip": "Profil importieren (.rcmprofile)",
            "no_profiles": "Noch keine Profile — erstelle das erste.",
            "no_description": "Keine Beschreibung",
            "count_one": "1 Konfiguration",
            "count_many": "{count} Konfigurationen",
            "status_ready": "Bereit",
            "status_missing": "{count} Konfiguration(en) nicht gefunden",
            "name": "Name",
            "name_placeholder": "z. B. Tryhard",
            "description": "Beschreibung",
            "description_placeholder": "Optional",
            "capture_note": "Profilkonfigurationen (vorausgewählt: in Fleasion aktiv)",
            "create_title": "Neues Profil",
            "edit_title": "Profil bearbeiten",
            "export_dialog": "Profil exportieren",
            "import_dialog": "Profil importieren",
            "name_required": "Der Profilname ist erforderlich.",
            "already_exists": "Ein Profil « {name} » existiert bereits.",
            "not_found": "Profil nicht gefunden: {name}",
            "import_invalid": "Ungültige Profildatei: {path}",
        },
        "theme": {
            "dark": "Dunkel",
            "light": "Hell",
            "blue": "Blau",
            "red": "Rot",
            "green": "Grün",
            "purple": "Violett",
            "midnight": "Mitternacht",
            "custom": "Benutzerdefiniert",
            "custom_title": "Benutzerdefiniertes Thema",
            "primary": "Primärfarbe",
            "secondary": "Sekundärfarbe",
            "accent": "Akzent",
            "background": "Hintergrund",
            "gradient": "Verlauf",
            "gradient_angle": "Verlaufswinkel",
            "pick_color": "Farbe wählen",
        },
        "settings": {
            "theme": "Thema",
            "shortcuts_title": "Tastenkürzel",
        },
        "shortcuts": {
            "open_search": "Suche öffnen",
            "go_home": "Zur Startseite",
            "verify_config": "Ausgewählte Konfiguration prüfen",
            "toggle_config": "Ausgewählte Konfiguration aktivieren / deaktivieren",
        },
        "detection": {
            "deps_label": "Erkannte Abhängigkeiten: {deps}",
        },
        "toast": {
            "favorite_added": "Zu Favoriten hinzugefügt",
            "favorite_removed": "Aus Favoriten entfernt",
            "verify_ok": "Gültige Konfiguration",
            "verify_incomplete": "Unvollständige Konfiguration",
            "repair_ok": "Konfiguration repariert und geprüft",
            "repair_not_fixed": "Die Konfiguration ist weiterhin unvollständig",
            "profile_created": "Profil « {name} » erstellt",
            "profile_updated": "Profil « {name} » aktualisiert",
            "profile_deleted": "Profil « {name} » gelöscht",
            "profile_applied": "Profil « {name} » angewendet",
            "profile_partial": "Profil « {name} » teilweise angewendet — Fehler: {failed}",
            "profile_nothing_applied": "Keine Konfiguration des Profils konnte angewendet werden",
            "profile_exported": "Profil exportiert: {path}",
            "profile_imported": "Profil « {name} » importiert",
            "theme_applied": "Thema angewendet",
            "item_not_found": "Element nicht gefunden",
        },
        "confirm": {
            "profile_delete_title": "Profil löschen",
            "profile_delete_text": "Profil « {name} » löschen?",
            "profile_delete_info": "Die Bibliothekskonfigurationen werden nicht berührt.",
            "profile_missing_title": "Konfigurationen nicht gefunden",
            "profile_missing_text_one": "Das Profil « {name} » enthält 1 nicht gefundene Konfiguration.",
            "profile_missing_text_many": "Das Profil « {name} » enthält {count} nicht gefundene Konfigurationen.",
            "profile_missing_info": "Fehlende Konfigurationen:\n{files}\n\nDie übrigen Konfigurationen können angewendet werden.",
            "profile_continue": "Weiter",
        },
    },
    "it": {
        "search": {
            "page_title": "Cerca",
            "page_placeholder": "Cerca una configurazione…",
            "clear": "Cancella",
            "clear_tooltip": "Cancella la ricerca",
            "recents": "Recenti",
            "recents_subtitle": "Configurazioni usate di recente",
            "recent_item": "Recent",
            "no_recents": "Nessuna configurazione recente per ora.",
        },
        "favorites": {
            "filter_all": "Tutte",
            "filter_only": "Preferite",
            "filter_excluded": "Non preferite",
        },
        "card": {
            "favorite_add": "Aggiungi ai preferiti",
            "favorite_remove": "Rimuovi dai preferiti",
            "status_ready": "Pronta",
            "status_incomplete": "Incompleta",
            "status_error": "Errore",
            "status_active": "Attiva",
        },
        "config": {
            "verify": "VERIFICA",
            "verify_tooltip": "Verifica la configurazione (JSON, dipendenze, file, categoria)",
        },
        "verify": {
            "valid": "✓ Configurazione valida",
            "incomplete": "⚠ Configurazione incompleta",
            "deps_ok": "Dipendenze presenti",
            "usable_note": "La configurazione non funzionerà correttamente finché questi file non saranno presenti.",
            "missing_dependency": "{kind} mancante: {name}",
            "missing_file": "File mancante: {name}",
            "invalid_category": "Categoria non trovata",
            "no_json": "Nessun file JSON in questa configurazione.",
        },
        "repair": {
            "button": "Ripara",
            "button_tooltip": "Prova a riparare le dipendenze mancanti",
            "action_copy": "Copia {name}",
            "possible": "Riparazione possibile: {count} file{s} da copiare.",
            "impossible": "Impossibile riparare automaticamente.\n\nFile mancanti:\n{files}",
            "nothing": "Nulla da riparare.",
            "source_missing": "Origine non trovata: {name}",
            "copy_failed": "Impossibile copiare {name}: {detail}",
            "confirm_text": "L'applicazione copierà i file mancanti accanto alla configurazione.",
            "do": "Ripara",
            "partial": "Riparazione parziale:\n{errors}",
        },
        "profiles": {
            "title": "Profili",
            "subtitle": "Salva un gruppo di configurazioni e ripristinalo con un clic.",
            "create": "Crea profilo",
            "edit": "Modifica",
            "delete": "Elimina",
            "apply": "Applica",
            "export": "Esporta",
            "import": "Importa",
            "import_tooltip": "Importa un profilo (.rcmprofile)",
            "no_profiles": "Nessun profilo per ora — crea il primo.",
            "no_description": "Nessuna descrizione",
            "count_one": "1 configurazione",
            "count_many": "{count} configurazioni",
            "status_ready": "Pronto",
            "status_missing": "{count} configurazione/i non trovata/e",
            "name": "Nome",
            "name_placeholder": "es. Tryhard",
            "description": "Descrizione",
            "description_placeholder": "Opzionale",
            "capture_note": "Configurazioni del profilo (pre-selezionate: attive in Fleasion)",
            "create_title": "Nuovo profilo",
            "edit_title": "Modifica profilo",
            "export_dialog": "Esporta profilo",
            "import_dialog": "Importa un profilo",
            "name_required": "Il nome del profilo è obbligatorio.",
            "already_exists": "Esiste già un profilo « {name} ».",
            "not_found": "Profilo non trovato: {name}",
            "import_invalid": "File profilo non valido: {path}",
        },
        "theme": {
            "dark": "Scuro",
            "light": "Chiaro",
            "blue": "Blu",
            "red": "Rosso",
            "green": "Verde",
            "purple": "Viola",
            "midnight": "Mezzanotte",
            "custom": "Personalizzato",
            "custom_title": "Tema personalizzato",
            "primary": "Colore principale",
            "secondary": "Colore secondario",
            "accent": "Accento",
            "background": "Sfondo",
            "gradient": "Sfumatura",
            "gradient_angle": "Angolo della sfumatura",
            "pick_color": "Scegli un colore",
        },
        "settings": {
            "theme": "Tema",
            "shortcuts_title": "Scorciatoie da tastiera",
        },
        "shortcuts": {
            "open_search": "Apri la ricerca",
            "go_home": "Torna alla home",
            "verify_config": "Verifica la configurazione selezionata",
            "toggle_config": "Attiva / disattiva la configurazione selezionata",
        },
        "detection": {
            "deps_label": "Dipendenze rilevate: {deps}",
        },
        "toast": {
            "favorite_added": "Aggiunto ai preferiti",
            "favorite_removed": "Rimosso dai preferiti",
            "verify_ok": "Configurazione valida",
            "verify_incomplete": "Configurazione incompleta",
            "repair_ok": "Configurazione riparata e verificata",
            "repair_not_fixed": "La configurazione è ancora incompleta",
            "profile_created": "Profilo « {name} » creato",
            "profile_updated": "Profilo « {name} » aggiornato",
            "profile_deleted": "Profilo « {name} » eliminato",
            "profile_applied": "Profilo « {name} » applicato",
            "profile_partial": "Profilo « {name} » applicato parzialmente — errori: {failed}",
            "profile_nothing_applied": "Nessuna configurazione del profilo è stata applicata",
            "profile_exported": "Profilo esportato: {path}",
            "profile_imported": "Profilo « {name} » importato",
            "theme_applied": "Tema applicato",
            "item_not_found": "Elemento non trovato",
        },
        "confirm": {
            "profile_delete_title": "Elimina il profilo",
            "profile_delete_text": "Eliminare il profilo « {name} »?",
            "profile_delete_info": "Le configurazioni della libreria non vengono toccate.",
            "profile_missing_title": "Configurazioni non trovate",
            "profile_missing_text_one": "Il profilo « {name} » contiene 1 configurazione non trovata.",
            "profile_missing_text_many": "Il profilo « {name} » contiene {count} configurazioni non trovate.",
            "profile_missing_info": "Configurazioni mancanti:\n{files}\n\nLe altre configurazioni possono essere applicate.",
            "profile_continue": "Continua",
        },
    },
    "pt": {
        "search": {
            "page_title": "Pesquisar",
            "page_placeholder": "Pesquisar uma configuração…",
            "clear": "Limpar",
            "clear_tooltip": "Limpar a pesquisa",
            "recents": "Recentes",
            "recents_subtitle": "Configurações consultadas recentemente",
            "recent_item": "Recente",
            "no_recents": "Ainda não há configurações recentes.",
        },
        "favorites": {
            "filter_all": "Todas",
            "filter_only": "Favoritas",
            "filter_excluded": "Não favoritas",
        },
        "card": {
            "favorite_add": "Adicionar aos favoritos",
            "favorite_remove": "Remover dos favoritos",
            "status_ready": "Pronta",
            "status_incomplete": "Incompleta",
            "status_error": "Erro",
            "status_active": "Ativa",
        },
        "config": {
            "verify": "VERIFICAR",
            "verify_tooltip": "Verificar a configuração (JSON, dependências, arquivos, categoria)",
        },
        "verify": {
            "valid": "✓ Configuração válida",
            "incomplete": "⚠ Configuração incompleta",
            "deps_ok": "Dependências presentes",
            "usable_note": "A configuração não funcionará corretamente enquanto estes arquivos não estiverem presentes.",
            "missing_dependency": "{kind} ausente: {name}",
            "missing_file": "Arquivo ausente: {name}",
            "invalid_category": "Categoria não encontrada",
            "no_json": "Nenhum arquivo JSON nesta configuração.",
        },
        "repair": {
            "button": "Reparar",
            "button_tooltip": "Tentar reparar as dependências ausentes",
            "action_copy": "Copiar {name}",
            "possible": "Reparo possível: {count} arquivo{s} para copiar.",
            "impossible": "Não é possível reparar automaticamente.\n\nArquivo(s) ausente(s):\n{files}",
            "nothing": "Nada para reparar.",
            "source_missing": "Origem não encontrada: {name}",
            "copy_failed": "Não foi possível copiar {name}: {detail}",
            "confirm_text": "A aplicação copiará os arquivos ausentes para junto da configuração.",
            "do": "Reparar",
            "partial": "Reparo parcial:\n{errors}",
        },
        "profiles": {
            "title": "Perfis",
            "subtitle": "Guarde um grupo de configurações e restaure-o com um clique.",
            "create": "Criar perfil",
            "edit": "Editar",
            "delete": "Excluir",
            "apply": "Aplicar",
            "export": "Exportar",
            "import": "Importar",
            "import_tooltip": "Importar um perfil (.rcmprofile)",
            "no_profiles": "Ainda não há perfis — crie o primeiro.",
            "no_description": "Sem descrição",
            "count_one": "1 configuração",
            "count_many": "{count} configurações",
            "status_ready": "Pronto",
            "status_missing": "{count} configuração(ões) não encontrada(s)",
            "name": "Nome",
            "name_placeholder": "ex.: Tryhard",
            "description": "Descrição",
            "description_placeholder": "Opcional",
            "capture_note": "Configurações do perfil (pré-marcadas: ativas no Fleasion)",
            "create_title": "Novo perfil",
            "edit_title": "Editar perfil",
            "export_dialog": "Exportar perfil",
            "import_dialog": "Importar um perfil",
            "name_required": "O nome do perfil é obrigatório.",
            "already_exists": "Já existe um perfil « {name} ».",
            "not_found": "Perfil não encontrado: {name}",
            "import_invalid": "Arquivo de perfil inválido: {path}",
        },
        "theme": {
            "dark": "Escuro",
            "light": "Claro",
            "blue": "Azul",
            "red": "Vermelho",
            "green": "Verde",
            "purple": "Roxo",
            "midnight": "Meia-noite",
            "custom": "Personalizado",
            "custom_title": "Tema personalizado",
            "primary": "Cor principal",
            "secondary": "Cor secundária",
            "accent": "Acento",
            "background": "Fundo",
            "gradient": "Gradiente",
            "gradient_angle": "Ângulo do gradiente",
            "pick_color": "Escolher uma cor",
        },
        "settings": {
            "theme": "Tema",
            "shortcuts_title": "Atalhos de teclado",
        },
        "shortcuts": {
            "open_search": "Abrir a pesquisa",
            "go_home": "Voltar ao início",
            "verify_config": "Verificar a configuração selecionada",
            "toggle_config": "Ativar / desativar a configuração selecionada",
        },
        "detection": {
            "deps_label": "Dependências detectadas: {deps}",
        },
        "toast": {
            "favorite_added": "Adicionado aos favoritos",
            "favorite_removed": "Removido dos favoritos",
            "verify_ok": "Configuração válida",
            "verify_incomplete": "Configuração incompleta",
            "repair_ok": "Configuração reparada e verificada",
            "repair_not_fixed": "A configuração ainda está incompleta",
            "profile_created": "Perfil « {name} » criado",
            "profile_updated": "Perfil « {name} » atualizado",
            "profile_deleted": "Perfil « {name} » excluído",
            "profile_applied": "Perfil « {name} » aplicado",
            "profile_partial": "Perfil « {name} » aplicado parcialmente — erros: {failed}",
            "profile_nothing_applied": "Nenhuma configuração do perfil pôde ser aplicada",
            "profile_exported": "Perfil exportado: {path}",
            "profile_imported": "Perfil « {name} » importado",
            "theme_applied": "Tema aplicado",
            "item_not_found": "Elemento não encontrado",
        },
        "confirm": {
            "profile_delete_title": "Excluir o perfil",
            "profile_delete_text": "Excluir o perfil « {name} »?",
            "profile_delete_info": "As configurações da biblioteca não são afetadas.",
            "profile_missing_title": "Configurações não encontradas",
            "profile_missing_text_one": "O perfil « {name} » contém 1 configuração não encontrada.",
            "profile_missing_text_many": "O perfil « {name} » contém {count} configurações não encontradas.",
            "profile_missing_info": "Configurações ausentes:\n{files}\n\nAs outras configurações podem ser aplicadas.",
            "profile_continue": "Continuar",
        },
    },
    "nl": {
        "search": {
            "page_title": "Zoeken",
            "page_placeholder": "Zoek een configuratie…",
            "clear": "Wissen",
            "clear_tooltip": "Zoekopdracht wissen",
            "recents": "Recente",
            "recents_subtitle": "Recent gebruikte configuraties",
            "recent_item": "Recent",
            "no_recents": "Nog geen recente configuraties.",
        },
        "favorites": {
            "filter_all": "Alle",
            "filter_only": "Favorieten",
            "filter_excluded": "Geen favorieten",
        },
        "card": {
            "favorite_add": "Toevoegen aan favorieten",
            "favorite_remove": "Verwijderen uit favorieten",
            "status_ready": "Klaar",
            "status_incomplete": "Onvolledig",
            "status_error": "Fout",
            "status_active": "Actief",
        },
        "config": {
            "verify": "CONTROLEREN",
            "verify_tooltip": "Configuratie controleren (JSON, afhankelijkheden, bestanden, categorie)",
        },
        "verify": {
            "valid": "✓ Geldige configuratie",
            "incomplete": "⚠ Onvolledige configuratie",
            "deps_ok": "Afhankelijkheden aanwezig",
            "usable_note": "De configuratie werkt pas correct als deze bestanden aanwezig zijn.",
            "missing_dependency": "{kind} ontbreekt: {name}",
            "missing_file": "Ontbrekend bestand: {name}",
            "invalid_category": "Categorie niet gevonden",
            "no_json": "Geen JSON-bestand in deze configuratie.",
        },
        "repair": {
            "button": "Repareren",
            "button_tooltip": "Ontbrekende afhankelijkheden proberen te repareren",
            "action_copy": "{name} kopiëren",
            "possible": "Reparatie mogelijk: {count} bestand{s} te kopiëren.",
            "impossible": "Automatisch repareren niet mogelijk.\n\nOntbrekende bestanden:\n{files}",
            "nothing": "Niets te repareren.",
            "source_missing": "Bron niet gevonden: {name}",
            "copy_failed": "Kan {name} niet kopiëren: {detail}",
            "confirm_text": "De applicatie kopieert de ontbrekende bestanden naast de configuratie.",
            "do": "Repareren",
            "partial": "Gedeeltelijke reparatie:\n{errors}",
        },
        "profiles": {
            "title": "Profielen",
            "subtitle": "Sla een groep configuraties op en herstel ze met één klik.",
            "create": "Profiel maken",
            "edit": "Bewerken",
            "delete": "Verwijderen",
            "apply": "Toepassen",
            "export": "Exporteren",
            "import": "Importeren",
            "import_tooltip": "Een profiel importeren (.rcmprofile)",
            "no_profiles": "Nog geen profielen — maak het eerste.",
            "no_description": "Geen beschrijving",
            "count_one": "1 configuratie",
            "count_many": "{count} configuraties",
            "status_ready": "Klaar",
            "status_missing": "{count} configuratie(s) niet gevonden",
            "name": "Naam",
            "name_placeholder": "bijv. Tryhard",
            "description": "Beschrijving",
            "description_placeholder": "Optioneel",
            "capture_note": "Profielconfiguraties (vooraf aangevinkt: actief in Fleasion)",
            "create_title": "Nieuw profiel",
            "edit_title": "Profiel bewerken",
            "export_dialog": "Profiel exporteren",
            "import_dialog": "Een profiel importeren",
            "name_required": "De profielnaam is verplicht.",
            "already_exists": "Er bestaat al een profiel « {name} ».",
            "not_found": "Profiel niet gevonden: {name}",
            "import_invalid": "Ongeldig profielbestand: {path}",
        },
        "theme": {
            "dark": "Donker",
            "light": "Licht",
            "blue": "Blauw",
            "red": "Rood",
            "green": "Groen",
            "purple": "Paars",
            "midnight": "Middernacht",
            "custom": "Aangepast",
            "custom_title": "Aangepast thema",
            "primary": "Primaire kleur",
            "secondary": "Secundaire kleur",
            "accent": "Accent",
            "background": "Achtergrond",
            "gradient": "Verloop",
            "gradient_angle": "Verloophoek",
            "pick_color": "Kies een kleur",
        },
        "settings": {
            "theme": "Thema",
            "shortcuts_title": "Sneltoetsen",
        },
        "shortcuts": {
            "open_search": "Zoeken openen",
            "go_home": "Terug naar home",
            "verify_config": "Geselecteerde configuratie controleren",
            "toggle_config": "Geselecteerde configuratie activeren / deactiveren",
        },
        "detection": {
            "deps_label": "Gedetecteerde afhankelijkheden: {deps}",
        },
        "toast": {
            "favorite_added": "Toegevoegd aan favorieten",
            "favorite_removed": "Verwijderd uit favorieten",
            "verify_ok": "Geldige configuratie",
            "verify_incomplete": "Onvolledige configuratie",
            "repair_ok": "Configuratie gerepareerd en gecontroleerd",
            "repair_not_fixed": "De configuratie is nog steeds onvolledig",
            "profile_created": "Profiel « {name} » gemaakt",
            "profile_updated": "Profiel « {name} » bijgewerkt",
            "profile_deleted": "Profiel « {name} » verwijderd",
            "profile_applied": "Profiel « {name} » toegepast",
            "profile_partial": "Profiel « {name} » gedeeltelijk toegepast — fouten: {failed}",
            "profile_nothing_applied": "Geen enkele configuratie van het profiel kon worden toegepast",
            "profile_exported": "Profiel geëxporteerd: {path}",
            "profile_imported": "Profiel « {name} » geïmporteerd",
            "theme_applied": "Thema toegepast",
            "item_not_found": "Item niet gevonden",
        },
        "confirm": {
            "profile_delete_title": "Profiel verwijderen",
            "profile_delete_text": "Profiel « {name} » verwijderen?",
            "profile_delete_info": "De bibliotheekconfiguraties worden niet aangeraakt.",
            "profile_missing_title": "Configuraties niet gevonden",
            "profile_missing_text_one": "Het profiel « {name} » bevat 1 niet gevonden configuratie.",
            "profile_missing_text_many": "Het profiel « {name} » bevat {count} niet gevonden configuraties.",
            "profile_missing_info": "Ontbrekende configuraties:\n{files}\n\nDe andere configuraties kunnen worden toegepast.",
            "profile_continue": "Doorgaan",
        },
    },
    "pl": {
        "search": {
            "page_title": "Szukaj",
            "page_placeholder": "Szukaj konfiguracji…",
            "clear": "Wyczyść",
            "clear_tooltip": "Wyczyść wyszukiwanie",
            "recents": "Ostatnie",
            "recents_subtitle": "Ostatnio używane konfiguracje",
            "recent_item": "Ostatnia",
            "no_recents": "Brak ostatnich konfiguracji.",
        },
        "favorites": {
            "filter_all": "Wszystkie",
            "filter_only": "Ulubione",
            "filter_excluded": "Nieulubione",
        },
        "card": {
            "favorite_add": "Dodaj do ulubionych",
            "favorite_remove": "Usuń z ulubionych",
            "status_ready": "Gotowa",
            "status_incomplete": "Niekompletna",
            "status_error": "Błąd",
            "status_active": "Aktywna",
        },
        "config": {
            "verify": "SPRAWDŹ",
            "verify_tooltip": "Sprawdź konfigurację (JSON, zależności, pliki, kategoria)",
        },
        "verify": {
            "valid": "✓ Prawidłowa konfiguracja",
            "incomplete": "⚠ Niekompletna konfiguracja",
            "deps_ok": "Zależności obecne",
            "usable_note": "Konfiguracja nie będzie działać poprawnie, dopóki te pliki nie będą obecne.",
            "missing_dependency": "Brak {kind}: {name}",
            "missing_file": "Brakujący plik: {name}",
            "invalid_category": "Nie znaleziono kategorii",
            "no_json": "Brak pliku JSON w tej konfiguracji.",
        },
        "repair": {
            "button": "Napraw",
            "button_tooltip": "Spróbuj naprawić brakujące zależności",
            "action_copy": "Skopiuj {name}",
            "possible": "Naprawa możliwa: {count} plik{s} do skopiowania.",
            "impossible": "Automatyczna naprawa niemożliwa.\n\nBrakujące pliki:\n{files}",
            "nothing": "Nic do naprawy.",
            "source_missing": "Nie znaleziono źródła: {name}",
            "copy_failed": "Nie można skopiować {name}: {detail}",
            "confirm_text": "Aplikacja skopiuje brakujące pliki obok konfiguracji.",
            "do": "Napraw",
            "partial": "Częściowa naprawa:\n{errors}",
        },
        "profiles": {
            "title": "Profile",
            "subtitle": "Zapisz grupę konfiguracji i przywróć ją jednym kliknięciem.",
            "create": "Utwórz profil",
            "edit": "Edytuj",
            "delete": "Usuń",
            "apply": "Zastosuj",
            "export": "Eksportuj",
            "import": "Importuj",
            "import_tooltip": "Importuj profil (.rcmprofile)",
            "no_profiles": "Brak profili — utwórz pierwszy.",
            "no_description": "Brak opisu",
            "count_one": "1 konfiguracja",
            "count_many": "{count} konfiguracji",
            "status_ready": "Gotowy",
            "status_missing": "{count} konfiguracji nie znaleziono",
            "name": "Nazwa",
            "name_placeholder": "np. Tryhard",
            "description": "Opis",
            "description_placeholder": "Opcjonalne",
            "capture_note": "Konfiguracje profilu (zaznaczone: aktywne w Fleasion)",
            "create_title": "Nowy profil",
            "edit_title": "Edytuj profil",
            "export_dialog": "Eksportuj profil",
            "import_dialog": "Importuj profil",
            "name_required": "Nazwa profilu jest wymagana.",
            "already_exists": "Profil « {name} » już istnieje.",
            "not_found": "Nie znaleziono profilu: {name}",
            "import_invalid": "Nieprawidłowy plik profilu: {path}",
        },
        "theme": {
            "dark": "Ciemny",
            "light": "Jasny",
            "blue": "Niebieski",
            "red": "Czerwony",
            "green": "Zielony",
            "purple": "Fioletowy",
            "midnight": "Północ",
            "custom": "Własny",
            "custom_title": "Własny motyw",
            "primary": "Kolor główny",
            "secondary": "Kolor drugorzędny",
            "accent": "Akcent",
            "background": "Tło",
            "gradient": "Gradient",
            "gradient_angle": "Kąt gradientu",
            "pick_color": "Wybierz kolor",
        },
        "settings": {
            "theme": "Motyw",
            "shortcuts_title": "Skróty klawiszowe",
        },
        "shortcuts": {
            "open_search": "Otwórz wyszukiwanie",
            "go_home": "Wróć do strony głównej",
            "verify_config": "Sprawdź wybraną konfigurację",
            "toggle_config": "Aktywuj / dezaktywuj wybraną konfigurację",
        },
        "detection": {
            "deps_label": "Wykryte zależności: {deps}",
        },
        "toast": {
            "favorite_added": "Dodano do ulubionych",
            "favorite_removed": "Usunięto z ulubionych",
            "verify_ok": "Prawidłowa konfiguracja",
            "verify_incomplete": "Niekompletna konfiguracja",
            "repair_ok": "Konfiguracja naprawiona i sprawdzona",
            "repair_not_fixed": "Konfiguracja jest nadal niekompletna",
            "profile_created": "Utworzono profil « {name} »",
            "profile_updated": "Zaktualizowano profil « {name} »",
            "profile_deleted": "Usunięto profil « {name} »",
            "profile_applied": "Zastosowano profil « {name} »",
            "profile_partial": "Profil « {name} » zastosowany częściowo — błędy: {failed}",
            "profile_nothing_applied": "Żadna konfiguracja profilu nie została zastosowana",
            "profile_exported": "Wyeksportowano profil: {path}",
            "profile_imported": "Zaimportowano profil « {name} »",
            "theme_applied": "Zastosowano motyw",
            "item_not_found": "Nie znaleziono elementu",
        },
        "confirm": {
            "profile_delete_title": "Usuń profil",
            "profile_delete_text": "Usunąć profil « {name} »?",
            "profile_delete_info": "Konfiguracje biblioteki nie zostaną naruszone.",
            "profile_missing_title": "Nie znaleziono konfiguracji",
            "profile_missing_text_one": "Profil « {name} » zawiera 1 nieznalezioną konfigurację.",
            "profile_missing_text_many": "Profil « {name} » zawiera {count} nieznalezionych konfiguracji.",
            "profile_missing_info": "Brakujące konfiguracje:\n{files}\n\nPozostałe konfiguracje mogą zostać zastosowane.",
            "profile_continue": "Kontynuuj",
        },
    },
    "ru": {
        "search": {
            "page_title": "Поиск",
            "page_placeholder": "Поиск конфигурации…",
            "clear": "Очистить",
            "clear_tooltip": "Очистить поиск",
            "recents": "Недавние",
            "recents_subtitle": "Недавно использованные конфигурации",
            "recent_item": "Недавняя",
            "no_recents": "Пока нет недавних конфигураций.",
        },
        "favorites": {
            "filter_all": "Все",
            "filter_only": "Избранные",
            "filter_excluded": "Не избранные",
        },
        "card": {
            "favorite_add": "Добавить в избранное",
            "favorite_remove": "Убрать из избранного",
            "status_ready": "Готова",
            "status_incomplete": "Неполная",
            "status_error": "Ошибка",
            "status_active": "Активна",
        },
        "config": {
            "verify": "ПРОВЕРИТЬ",
            "verify_tooltip": "Проверить конфигурацию (JSON, зависимости, файлы, категория)",
        },
        "verify": {
            "valid": "✓ Действительная конфигурация",
            "incomplete": "⚠ Неполная конфигурация",
            "deps_ok": "Зависимости на месте",
            "usable_note": "Конфигурация не будет работать корректно, пока эти файлы не будут на месте.",
            "missing_dependency": "Отсутствует {kind}: {name}",
            "missing_file": "Отсутствующий файл: {name}",
            "invalid_category": "Категория не найдена",
            "no_json": "В этой конфигурации нет файлов JSON.",
        },
        "repair": {
            "button": "Исправить",
            "button_tooltip": "Попытаться исправить отсутствующие зависимости",
            "action_copy": "Скопировать {name}",
            "possible": "Исправление возможно: {count} файл{s} для копирования.",
            "impossible": "Автоматическое исправление невозможно.\n\nОтсутствующие файлы:\n{files}",
            "nothing": "Нечего исправлять.",
            "source_missing": "Источник не найден: {name}",
            "copy_failed": "Не удалось скопировать {name}: {detail}",
            "confirm_text": "Приложение скопирует отсутствующие файлы рядом с конфигурацией.",
            "do": "Исправить",
            "partial": "Частичное исправление:\n{errors}",
        },
        "profiles": {
            "title": "Профили",
            "subtitle": "Сохраните группу конфигураций и восстановите её одним кликом.",
            "create": "Создать профиль",
            "edit": "Изменить",
            "delete": "Удалить",
            "apply": "Применить",
            "export": "Экспорт",
            "import": "Импорт",
            "import_tooltip": "Импортировать профиль (.rcmprofile)",
            "no_profiles": "Пока нет профилей — создайте первый.",
            "no_description": "Нет описания",
            "count_one": "1 конфигурация",
            "count_many": "{count} конфигураций",
            "status_ready": "Готов",
            "status_missing": "{count} конфигураци(й) не найдено",
            "name": "Название",
            "name_placeholder": "напр. Tryhard",
            "description": "Описание",
            "description_placeholder": "Необязательно",
            "capture_note": "Конфигурации профиля (отмечены: активные во Fleasion)",
            "create_title": "Новый профиль",
            "edit_title": "Изменить профиль",
            "export_dialog": "Экспорт профиля",
            "import_dialog": "Импорт профиля",
            "name_required": "Требуется название профиля.",
            "already_exists": "Профиль « {name} » уже существует.",
            "not_found": "Профиль не найден: {name}",
            "import_invalid": "Недопустимый файл профиля: {path}",
        },
        "theme": {
            "dark": "Тёмный",
            "light": "Светлый",
            "blue": "Синий",
            "red": "Красный",
            "green": "Зелёный",
            "purple": "Фиолетовый",
            "midnight": "Полночь",
            "custom": "Свой",
            "custom_title": "Своя тема",
            "primary": "Основной цвет",
            "secondary": "Второстепенный цвет",
            "accent": "Акцент",
            "background": "Фон",
            "gradient": "Градиент",
            "gradient_angle": "Угол градиента",
            "pick_color": "Выбрать цвет",
        },
        "settings": {
            "theme": "Тема",
            "shortcuts_title": "Сочетания клавиш",
        },
        "shortcuts": {
            "open_search": "Открыть поиск",
            "go_home": "Вернуться на главную",
            "verify_config": "Проверить выбранную конфигурацию",
            "toggle_config": "Активировать / деактивировать выбранную конфигурацию",
        },
        "detection": {
            "deps_label": "Обнаруженные зависимости: {deps}",
        },
        "toast": {
            "favorite_added": "Добавлено в избранное",
            "favorite_removed": "Убрано из избранного",
            "verify_ok": "Действительная конфигурация",
            "verify_incomplete": "Неполная конфигурация",
            "repair_ok": "Конфигурация исправлена и проверена",
            "repair_not_fixed": "Конфигурация всё ещё неполная",
            "profile_created": "Профиль « {name} » создан",
            "profile_updated": "Профиль « {name} » обновлён",
            "profile_deleted": "Профиль « {name} » удалён",
            "profile_applied": "Профиль « {name} » применён",
            "profile_partial": "Профиль « {name} » применён частично — ошибки: {failed}",
            "profile_nothing_applied": "Ни одна конфигурация профиля не была применена",
            "profile_exported": "Профиль экспортирован: {path}",
            "profile_imported": "Профиль « {name} » импортирован",
            "theme_applied": "Тема применена",
            "item_not_found": "Элемент не найден",
        },
        "confirm": {
            "profile_delete_title": "Удалить профиль",
            "profile_delete_text": "Удалить профиль « {name} »?",
            "profile_delete_info": "Конфигурации библиотеки не затрагиваются.",
            "profile_missing_title": "Конфигурации не найдены",
            "profile_missing_text_one": "Профиль « {name} » содержит 1 ненайденную конфигурацию.",
            "profile_missing_text_many": "Профиль « {name} » содержит {count} ненайденных конфигураций.",
            "profile_missing_info": "Отсутствующие конфигурации:\n{files}\n\nОстальные конфигурации можно применить.",
            "profile_continue": "Продолжить",
        },
    },
    "tr": {
        "search": {
            "page_title": "Ara",
            "page_placeholder": "Bir yapılandırma ara…",
            "clear": "Temizle",
            "clear_tooltip": "Aramayı temizle",
            "recents": "Son kullanılanlar",
            "recents_subtitle": "Son kullanılan yapılandırmalar",
            "recent_item": "Son",
            "no_recents": "Henüz son kullanılan yapılandırma yok.",
        },
        "favorites": {
            "filter_all": "Tümü",
            "filter_only": "Favoriler",
            "filter_excluded": "Favori olmayanlar",
        },
        "card": {
            "favorite_add": "Favorilere ekle",
            "favorite_remove": "Favorilerden çıkar",
            "status_ready": "Hazır",
            "status_incomplete": "Eksik",
            "status_error": "Hata",
            "status_active": "Aktif",
        },
        "config": {
            "verify": "DOĞRULA",
            "verify_tooltip": "Yapılandırmayı doğrula (JSON, bağımlılıklar, dosyalar, kategori)",
        },
        "verify": {
            "valid": "✓ Geçerli yapılandırma",
            "incomplete": "⚠ Eksik yapılandırma",
            "deps_ok": "Bağımlılıklar mevcut",
            "usable_note": "Bu dosyalar mevcut olana kadar yapılandırma doğru çalışmayacaktır.",
            "missing_dependency": "Eksik {kind}: {name}",
            "missing_file": "Eksik dosya: {name}",
            "invalid_category": "Kategori bulunamadı",
            "no_json": "Bu yapılandırmada JSON dosyası yok.",
        },
        "repair": {
            "button": "Onar",
            "button_tooltip": "Eksik bağımlılıkları onarmayı dene",
            "action_copy": "{name} kopyala",
            "possible": "Onarım mümkün: {count} dosya{s} kopyalanacak.",
            "impossible": "Otomatik onarım mümkün değil.\n\nEksik dosya(lar):\n{files}",
            "nothing": "Onarılacak bir şey yok.",
            "source_missing": "Kaynak bulunamadı: {name}",
            "copy_failed": "{name} kopyalanamadı: {detail}",
            "confirm_text": "Uygulama eksik dosyaları yapılandırmanın yanına kopyalayacak.",
            "do": "Onar",
            "partial": "Kısmi onarım:\n{errors}",
        },
        "profiles": {
            "title": "Profiller",
            "subtitle": "Bir yapılandırma grubunu kaydedin ve tek tıkla geri yükleyin.",
            "create": "Profil oluştur",
            "edit": "Düzenle",
            "delete": "Sil",
            "apply": "Uygula",
            "export": "Dışa aktar",
            "import": "İçe aktar",
            "import_tooltip": "Bir profil içe aktar (.rcmprofile)",
            "no_profiles": "Henüz profil yok — ilkini oluşturun.",
            "no_description": "Açıklama yok",
            "count_one": "1 yapılandırma",
            "count_many": "{count} yapılandırma",
            "status_ready": "Hazır",
            "status_missing": "{count} yapılandırma bulunamadı",
            "name": "Ad",
            "name_placeholder": "örn. Tryhard",
            "description": "Açıklama",
            "description_placeholder": "İsteğe bağlı",
            "capture_note": "Profil yapılandırmaları (önceden işaretli: Fleasion'da aktif)",
            "create_title": "Yeni profil",
            "edit_title": "Profili düzenle",
            "export_dialog": "Profili dışa aktar",
            "import_dialog": "Bir profil içe aktar",
            "name_required": "Profil adı gereklidir.",
            "already_exists": "« {name} » adlı bir profil zaten var.",
            "not_found": "Profil bulunamadı: {name}",
            "import_invalid": "Geçersiz profil dosyası: {path}",
        },
        "theme": {
            "dark": "Koyu",
            "light": "Açık",
            "blue": "Mavi",
            "red": "Kırmızı",
            "green": "Yeşil",
            "purple": "Mor",
            "midnight": "Gece yarısı",
            "custom": "Özel",
            "custom_title": "Özel tema",
            "primary": "Ana renk",
            "secondary": "İkincil renk",
            "accent": "Vurgu",
            "background": "Arka plan",
            "gradient": "Degrade",
            "gradient_angle": "Degrade açısı",
            "pick_color": "Bir renk seç",
        },
        "settings": {
            "theme": "Tema",
            "shortcuts_title": "Klavye kısayolları",
        },
        "shortcuts": {
            "open_search": "Aramayı aç",
            "go_home": "Ana sayfaya dön",
            "verify_config": "Seçili yapılandırmayı doğrula",
            "toggle_config": "Seçili yapılandırmayı etkinleştir / devre dışı bırak",
        },
        "detection": {
            "deps_label": "Algılanan bağımlılıklar: {deps}",
        },
        "toast": {
            "favorite_added": "Favorilere eklendi",
            "favorite_removed": "Favorilerden çıkarıldı",
            "verify_ok": "Geçerli yapılandırma",
            "verify_incomplete": "Eksik yapılandırma",
            "repair_ok": "Yapılandırma onarıldı ve doğrulandı",
            "repair_not_fixed": "Yapılandırma hâlâ eksik",
            "profile_created": "« {name} » profili oluşturuldu",
            "profile_updated": "« {name} » profili güncellendi",
            "profile_deleted": "« {name} » profili silindi",
            "profile_applied": "« {name} » profili uygulandı",
            "profile_partial": "« {name} » profili kısmen uygulandı — hatalar: {failed}",
            "profile_nothing_applied": "Profilin hiçbir yapılandırması uygulanamadı",
            "profile_exported": "Profil dışa aktarıldı: {path}",
            "profile_imported": "« {name} » profili içe aktarıldı",
            "theme_applied": "Tema uygulandı",
            "item_not_found": "Öğe bulunamadı",
        },
        "confirm": {
            "profile_delete_title": "Profili sil",
            "profile_delete_text": "« {name} » profili silinsin mi?",
            "profile_delete_info": "Kitaplıktaki yapılandırmalar etkilenmez.",
            "profile_missing_title": "Yapılandırmalar bulunamadı",
            "profile_missing_text_one": "« {name} » profili 1 bulunamayan yapılandırma içeriyor.",
            "profile_missing_text_many": "« {name} » profili {count} bulunamayan yapılandırma içeriyor.",
            "profile_missing_info": "Eksik yapılandırmalar:\n{files}\n\nDiğer yapılandırmalar yine de uygulanabilir.",
            "profile_continue": "Devam et",
        },
    },
}


def deep_merge(target: dict, additions: dict) -> bool:
    changed = False
    for key, value in additions.items():
        if isinstance(value, dict):
            child = target.setdefault(key, {})
            if not isinstance(child, dict):
                child = {}
                target[key] = child
            changed = deep_merge(child, value) or changed
        else:
            if key not in target:
                target[key] = value
                changed = True
    return changed


def build_lang(lang: str) -> dict:
    import copy

    if lang == "fr":
        return _fr()
    if lang == "en":
        return copy.deepcopy(_BASE)
    patch = _LANG_PATCHES.get(lang)
    base = copy.deepcopy(_BASE)
    if patch:
        deep_merge(base, patch)
    return base


def main() -> None:
    for lang in ("fr", "en", "es", "de", "it", "pt", "nl", "pl", "ru", "tr"):
        path = TRANS / f"{lang}.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        additions = build_lang(lang)
        changed = deep_merge(data, additions)
        if changed:
            path.write_text(
                json.dumps(data, indent=4, ensure_ascii=False) + "\n",
                encoding="utf-8",
            )
            print(f"{lang}: keys added")
        else:
            print(f"{lang}: nothing to add")


if __name__ == "__main__":
    main()
